name: vault-pki-test

services:
  vault:
    image: vault
    command: vault server -dev
    ports: [8200:8200]
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root

  init-bin:
    image: curlimages/curl
    volumes: [.:/tmp]
    working_dir: /tmp
    entrypoint: ["./script/deps.sh"]
    user: "${UID:-1000}"

  init-vault:
    image: vault
    volumes: [.:/tmp]
    working_dir: /tmp
    entrypoint: ["./script/pki.sh"]
    user: "${UID:-1000}"
    environment:
      VAULT_TOKEN: root
      VAULT_ADDR: http://vault:8200
    depends_on:
      init-bin:
        condition: service_completed_successfully
      vault:
        condition: service_started

  init-nginx:
    image: kubler/openssl
    volumes: [.:/tmp]
    working_dir: /tmp
    entrypoint: ["./script/server-cert.sh"]
    user: "${UID:-1000}"

  nginx:
    image: nginx
    command: nginx-debug -g 'daemon off;'
    ports: [8443:443]
    volumes:
      - ./certs:/etc/nginx/certificates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      init-nginx:
        condition: service_completed_successfully
      init-vault:
        condition: service_completed_successfully
